id: I041D994C
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T20:35:40.513169'
last_modified: '2022-06-18T20:35:40.513181'
parser: null
source_metadata:
  title: Hagiography of Glang thang spyan snga Kun dga rdo rje (1424–1477/78?)
  author: gser mdog paN chen shAkya mchog ldan/
  description: 'Digital version 4.0 {Wylie}; WYLIE COPY of master xml (completed:
    2012-09); head entries supplemented and linebreaks encoded, revision in process,
    no thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:Volker Caumanns (vc)
  - Editorial process:Volker Caumanns (vc), Mathias Fermer (mf)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:-
  - Revisions/Corrections:Volker Caumanns (vc)
  text_witnesses: https://sakyaresearch.org/sources/362
  bases:
    eb61:
      title: Hagiography of Glang thang spyan snga Kun dga rdo rje (1424–1477/78?)
      order: 1
      base_file: eb61.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
